Repository Ayushjhawar8/Sorting-Visualiser, pull requests merged in 2025-04, with the labels that each got.

#73 implemented-dynamic floating particle in the background in the Dark mode (Using Canvas API)
  css/style.css
  index.html
  scripts/app.js
Labels: Hard, apertre2.0

#75 Implemented Particle animation on both mode , integrated with toggle response.( ISSUE NO- #74 )
  scripts/app.js
  scripts/darkmode.js
Labels: Hard, apertre2.0

#78 Update style.css
  css/style.css
Labels: Easy, apertre2.0

#79 Refresh button added with correct functionality, which reinitialize the Sorting Visualizer. (Issue no-#77)
  css/style.css
  index.html
  scripts/app.js
Labels: Medium, apertre2.0

#81 The styling and appearance of the time complexity information improved significantly . (ISSUE no- #80 )
  css/style.css
  index.html
  scripts/app.js
Labels: Medium, apertre2.0

#88 "About The App" Popover card is Implemented for Application Overview. (Issue no- #83)
  css/style.css
  index.html
Labels: Medium, apertre2.0

#87 Update the README
  README.md
  public/Image1.png
  public/Image2.png
  public/Image3.png
  public/Image4.png
Labels: apertre2.0, Doc

#89 added a new theme toggle button (dark/light mode) Issue no #85
  css/style.css
  index.html
Labels: Medium, apertre2.0

#92 fix theme toggle btn responsive in all devices
  css/style.css
Labels: Medium, apertre2.0

#94 Update style.css
  css/style.css
Labels: Medium, apertre2.0

#96 Improve Main Container Visibility Across Devices
  css/style.css
Labels: Medium, apertre2.0

#98 Fix/theme persistent
  index.html
  scripts/darkmode.js
Labels: Medium, apertre2.0
