Repository Ayushjhawar8/Sorting-Visualiser, pull requests merged in 2025-03, with the labels that each got.

#15 Increase visualizer width
  Sorting-Visualiser-main/css/style.css
  Sorting-Visualiser-main/index.html
Labels: enhancement, apertre2.0

#17 Implement custom array size and speed multiplier
  Sorting-Visualiser-main/index.html
  Sorting-Visualiser-main/scripts/app.js
  Sorting-Visualiser-main/scripts/helper.js
Labels: Medium, apertre2.0

#18 Implemented dark mode feature
  Sorting-Visualiser-main/css/style.css
  Sorting-Visualiser-main/index.html
  Sorting-Visualiser-main/scripts/darkmode.js
Labels: Medium, apertre2.0

#29 added 404 page
  404.html
Labels: Medium, apertre2.0

#31 Readme File Update
  README.md
  public/img1.png
  public/img2.png
Labels: Medium, apertre2.0

#44 improved ui
  css/style.css
Labels: Medium, apertre2.0

#45 Fix bug: Ai Chatbot is no longer functional
  scripts/app.js
Labels: Hard, apertre2.0

#47 fix bug: Long Processing Time for Large Arrays with User Input
  scripts/app.js
Labels: Hard, apertre2.0

#50 Add issue and pull request templates for better contribution guidelines
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Medium, apertre2.0

#51 bug: Value beneath each cell is coming wrong
  scripts/app.js
  scripts/helper.js
Labels: Medium, apertre2.0

#55 Hide cell values when array size exceeds 90
  scripts/app.js
Labels: Medium, apertre2.0

#57 Add dynamic option to size menu for random list generation
  scripts/app.js
Labels: Medium, apertre2.0

#56 Feat/add sort option
  index.html
  scripts/helper.js
  scripts/sort-algorithms.js
Labels: Hard, apertre2.0

#61 back to top
  README.md
Labels: apertre2.0, Doc

#68 Fix/span UI
  scripts/app.js
  scripts/helper.js
  scripts/sort-algorithms.js
Labels: Medium, apertre2.0

#69 Fix input validation in randomList function to handle null values
  scripts/app.js
Labels: Medium, apertre2.0

#71 sound effects
  scripts/sort-algorithms.js
  sound.wav
Labels: Hard, apertre2.0
